=== shornabho/web-technologies-lab/Lab6/production-list.dtd
<!ELEMENT production-list (production+)>
<!ELEMENT production (number,name,synopsis,director,playwright,cast-list)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT synopsis (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT playwright (#PCDATA)>
<!ELEMENT cast-list (cast+)>
<!ELEMENT cast (cast-name)>
<!ELEMENT cast-name (#PCDATA)>

=== shornabho/web-technologies-lab/Lab6/plays.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl" ?>
<!DOCTYPE production-list SYSTEM "production-list.dtd">
<production-list>
  <production>
    <number>1</number>
    <name>Doosra Adhyaay</name>
    <synopsis>What happens when a simple woman like “Neerja” emotions dares to look for love outside her marriage from a man who is fearless and full of life “Abhay”. Love though, is not a simple word, as their story proceeds it takes us through an unimaginable complexity of unsaid emotions where Reality merely becomes an imagination of memories. Love is seen in yet another shade where it does survive the harsh realities of life but looses it self to the inner demons of the soul.</synopsis>
    <director>Avneesh Mishra</director>
    <playwright>Ajay Shukla</playwright>
    <cast-list>
      <cast>
        <cast-name>Shashi Bhushan Chaturvedi</cast-name>
      </cast>
      <cast>
        <cast-name>Ananya Purkayastha</cast-name>
      </cast>
    </cast-list>
  </production>
  <production>
    <number>2</number>
    <name>Blueticks</name>
    <synopsis>
      The internet has simplified ‘finding love’ but complicated ‘staying in it’ Relationships have transformed from cozy couples to curious love triangles, boy, girl and the notorious smartphone.
      Blue Ticks explores this bizarre chemistry between love and technology and takes you back to the good old days when messages were whispered and going viral wasn’t a happy thing.
      Roll on the floor laughing with the actors in this rib tickling performance that is sure to leave you feeling nostalgic.
    </synopsis>
    <director>Roshan Shetty</director>
    <playwright>Roshan Shetty</playwright>
    <cast-list>
      <cast>
        <cast-name>Roshan Shetty</cast-name>
      </cast>
      <cast>
        <cast-name>Vandana Bhushan</cast-name>
      </cast>
      <cast>
        <cast-name>Nishil Kamalan</cast-name>
      </cast>
      <cast>
        <cast-name>Kush Jobanputra</cast-name>
      </cast>
      <cast>
        <cast-name>Shubhin Kant</cast-name>
      </cast>
      <cast>
        <cast-name>Suraj Maurya</cast-name>
      </cast>
      <cast>
        <cast-name>Shonita Joshi</cast-name>
      </cast>
      <cast>
        <cast-name>Mudita Shauq</cast-name>
      </cast>
      
    </cast-list>
  </production>
  <production>
    <number>3</number>
    <name>The Great Raja Master Drama Company</name>
    <synopsis>The Great Raja Master Drama Company is about Raja Master who is a tailor Master by profession. Not only is Tailoring his profession, but it is also his legacy handed down to him by his Father and Grand-father and his tailoring shop is more than 60 years in the business. However, Raja Master has noticed that off-late his tailoring shop is not doing too well and the clientele has dropped for various reasons. In a flash of inspiration he decides that The Great Raja Master Tailor Company will now become The Great Raja Master Drama Company. This Drama Company will also give vent to the Creative streak within him, long suppressed by his father. And Raja Master decides that the Tailor Masters working for him are good enough to act for his Drama Company. Now what happens on opening night of the first play production of The Great Raja Master Drama Company is what this play is all about. The mishaps and the Comedy that happen as the Tailor masters try to put up a Professional piece of Drama and miserably fail in doing so and finally put paid to the Creative aspirations of Raja Master. The sense of fun and comedy in this play is heightened by the fact that this play is a total musical with many songs using the folk form of Nautanki. This play employs the form of a play within a play and finally ends with Raja Master realizing doing a Play is not all easy and he was better off in his Tailoring Profession.</synopsis>
    <director>Avneesh Mishra</director>
    <playwright>Dinesh Bharti</playwright>
    <cast-list>
      <cast>
        <cast-name>Hemant Pandey</cast-name>
      </cast>
      <cast>
        <cast-name>Narottam Bain</cast-name>
      </cast>
      <cast>
        <cast-name>Rana Pratap Sengar</cast-name>
      </cast>
      <cast>
        <cast-name>Shashi Bhushan Chaturvedi</cast-name>
      </cast>
      <cast>
        <cast-name>Nirmala J Chandra</cast-name>
      </cast>
      <cast>
        <cast-name>Narottam Bain</cast-name>
      </cast>
      <cast>
        <cast-name>Kritika Pande</cast-name>
      </cast>
      <cast>
        <cast-name>Vipin Heero</cast-name>
      </cast>
    </cast-list>
  </production>
</production-list>
